/* =========================================================
   나는 어떤 창업가일까? - script.js
   초보자용 한글 주석 포함
   ========================================================= */

/* =========================================================
   ★★★ Supabase 설정 — 여기 두 줄만 바꾸면 됩니다 ★★★

   [값을 어디서 찾나요?]
   supabase.com 로그인 → 내 프로젝트 선택
   → 왼쪽 아래 Project Settings → API 메뉴
     · Project URL      을 복사해 SUPABASE_URL 에 붙여넣기
     · anon public 키   를 복사해 SUPABASE_ANON_KEY 에 붙여넣기

   ※ anon public 키는 브라우저에 공개되는 것이 정상인 '공개용 키'입니다.
      단, service_role 키는 절대 여기에 넣으면 안 됩니다.
      (service_role 키는 모든 데이터를 지울 수 있는 관리자 키입니다)
   ========================================================= */

// ↓↓↓ 여기에 본인의 Supabase 프로젝트 URL 을 넣으세요 ↓↓↓
const SUPABASE_URL = "https://ihxhbiqpguahmftgedka.supabase.co";

// ↓↓↓ 여기에 본인의 anon public 키를 넣으세요 ↓↓↓
const SUPABASE_ANON_KEY = "sb_publishable_H0mEZ30L0mlqEX6BCixcJw_qt4YsNXO";

/* ---------------------------------------------------------
   [Supabase 테이블 만들기]
   Supabase 대시보드 → SQL Editor 에 아래 내용을 붙여넣고 RUN 하세요.

   create table test_results (
     id           bigint generated by default as identity primary key,
     nickname     text,
     result_type  text,
     idea_score   int,
     action_score int,
     data_score   int,
     people_score int,
     created_at   timestamptz default now()
   );

   -- 보안 설정(RLS)을 켜고, 누구나 '저장만' 할 수 있게 허용합니다.
   alter table test_results enable row level security;

   create policy "누구나 결과 저장 가능"
     on test_results for insert
     to anon
     with check (true);

   -- 전체 참여자 통계를 보여주려면 '읽기' 권한도 필요합니다.
   create policy "누구나 통계 조회 가능"
     on test_results for select
     to anon
     using (true);
--------------------------------------------------------- */

/* ---------------------------------------------------------
   1) 질문 데이터
   - 질문 12개를 배열(리스트) 형태로 만들어 둡니다.
   - 각 질문(q) 안에는 선택지 4개(options)가 들어 있습니다.
   - 각 선택지의 type 은 1점을 받을 유형 코드입니다.
     IDEA(아이디어) / ACTION(실행) / DATA(데이터) / PEOPLE(관계)

   ★ 설계 규칙 3가지
     (1) 모든 문항은 정답이 없는 성향 질문입니다.
     (2) 한 문항의 선택지 4개는 네 유형에 정확히 1점씩 연결됩니다.
         → 12문항이면 총점은 항상 12점, 유형별 최대 12점입니다.
     (3) 유형이 나오는 '순서'를 문항마다 바꿔 두었습니다.
         사람은 첫 번째 선택지를 더 많이 고르는 경향이 있어서,
         순서를 고정하면 특정 유형이 유리해지기 때문입니다.
         (각 유형이 1~4번 자리에 정확히 3번씩 등장하도록 배치)
--------------------------------------------------------- */
const questions = [
  {
    // 주제 1. 아이디어가 생겼을 때 행동  (순서: IDEA-ACTION-DATA-PEOPLE)
    q: "좋은 사업 아이디어가 떠올랐습니다. 가장 먼저 무엇을 하나요?",
    options: [
      { text: "이 아이디어가 어디까지 커질 수 있을지 더 그려본다", type: "IDEA" },
      { text: "작게라도 일단 만들어서 시장에 내놓아 본다", type: "ACTION" },
      { text: "시장 규모와 경쟁 현황부터 찾아서 정리해본다", type: "DATA" },
      { text: "주변 사람들에게 설명해보고 반응을 들어본다", type: "PEOPLE" }
    ]
  },
  {
    // 주제 2. 사업에서 중요하게 생각하는 것  (순서: ACTION-DATA-PEOPLE-IDEA)
    q: "사업을 할 때 가장 중요하다고 생각하는 것은 무엇인가요?",
    options: [
      { text: "남들보다 먼저 움직이는 실행 속도", type: "ACTION" },
      { text: "근거 있는 판단과 탄탄한 수익 구조", type: "DATA" },
      { text: "함께하는 팀과 고객에게 쌓이는 신뢰", type: "PEOPLE" },
      { text: "우리만 할 수 있는 차별화된 아이디어", type: "IDEA" }
    ]
  },
  {
    // 주제 3. 팀에서 맡는 역할  (순서: DATA-PEOPLE-IDEA-ACTION)
    q: "팀에서 일할 때 자연스럽게 맡게 되는 역할은 무엇인가요?",
    options: [
      { text: "자료와 숫자를 정리해 판단 기준을 만드는 역할", type: "DATA" },
      { text: "팀원 사이를 조율하고 분위기를 이끄는 역할", type: "PEOPLE" },
      { text: "새로운 방향과 아이디어를 제안하는 역할", type: "IDEA" },
      { text: "결정을 내리고 일정을 밀고 나가는 역할", type: "ACTION" }
    ]
  },
  {
    // 주제 4. 문제가 생겼을 때 행동  (순서: PEOPLE-IDEA-ACTION-DATA)
    q: "사업 중에 예상치 못한 문제가 생겼습니다. 어떻게 하나요?",
    options: [
      { text: "팀원이나 멘토와 상의하며 함께 답을 찾는다", type: "PEOPLE" },
      { text: "지금까지와 다른 새로운 해결책을 떠올려본다", type: "IDEA" },
      { text: "할 수 있는 것부터 바로 손을 대기 시작한다", type: "ACTION" },
      { text: "원인을 데이터로 분석해 정확히 짚어낸다", type: "DATA" }
    ]
  },
  {
    // 주제 5. 제품 출시 방식  (순서: DATA-IDEA-PEOPLE-ACTION)
    q: "제품의 첫 버전을 세상에 내놓는다면 어떤 방식인가요?",
    options: [
      { text: "성과를 측정할 지표를 먼저 설계해두고 내놓는다", type: "DATA" },
      { text: "남들과 확실히 다른 컨셉을 담아서 내놓는다", type: "IDEA" },
      { text: "소수의 고객과 함께 다듬어가며 내놓는다", type: "PEOPLE" },
      { text: "부족한 점이 있어도 빨리 내놓고 고쳐간다", type: "ACTION" }
    ]
  },
  {
    // 주제 6. 경쟁자 대응  (순서: IDEA-PEOPLE-ACTION-DATA)
    q: "우리와 비슷한 제품을 파는 경쟁자가 나타났습니다.",
    options: [
      { text: "경쟁이 없는 새로운 영역을 찾아 옮겨간다", type: "IDEA" },
      { text: "기존 고객과의 관계를 더 단단하게 만든다", type: "PEOPLE" },
      { text: "더 빠르게 움직여 시장을 먼저 차지한다", type: "ACTION" },
      { text: "경쟁사를 분석해 우리가 이길 지점을 찾는다", type: "DATA" }
    ]
  },
  {
    // 주제 7. 고객 불만 대응  (순서: PEOPLE-ACTION-DATA-IDEA)
    q: "고객에게 강한 불만 후기가 들어왔습니다. 어떻게 대응하나요?",
    options: [
      { text: "직접 연락해 무엇이 불편했는지 충분히 듣는다", type: "PEOPLE" },
      { text: "고칠 수 있는 부분부터 바로 수정해 반영한다", type: "ACTION" },
      { text: "비슷한 불만 사례를 모아 공통 원인을 찾는다", type: "DATA" },
      { text: "이 불만을 계기로 방식 자체를 새로 설계한다", type: "IDEA" }
    ]
  },
  {
    // 주제 8. 새로운 기술 대응  (순서: ACTION-DATA-IDEA-PEOPLE)
    q: "업계에 새로운 기술이 빠르게 퍼지고 있습니다. 나는?",
    options: [
      { text: "일단 직접 써보면서 우리 일에 적용해본다", type: "ACTION" },
      { text: "실제 효과와 비용을 따져보고 도입을 정한다", type: "DATA" },
      { text: "이 기술로 무엇을 새로 만들 수 있을지 상상한다", type: "IDEA" },
      { text: "먼저 써본 사람들의 이야기를 들어보고 판단한다", type: "PEOPLE" }
    ]
  },
  {
    // 주제 9. 투자금 활용  (순서: PEOPLE-DATA-ACTION-IDEA)
    q: "투자금 1억 원이 들어왔습니다. 어디에 가장 먼저 쓰나요?",
    options: [
      { text: "좋은 사람을 채용하고 파트너를 확보하는 데 쓴다", type: "PEOPLE" },
      { text: "채널별 효율을 측정하며 나눠서 집행한다", type: "DATA" },
      { text: "제품 개발과 영업에 곧바로 투입한다", type: "ACTION" },
      { text: "새로운 시도와 실험에 과감하게 쓴다", type: "IDEA" }
    ]
  },
  {
    // 주제 10. 실패 가능성 대응  (순서: DATA-ACTION-IDEA-PEOPLE)
    q: "이 사업이 실패할 수도 있다는 생각이 들 때, 나는?",
    options: [
      { text: "위험 요소를 미리 계산해 대비책을 만들어둔다", type: "DATA" },
      { text: "실패해도 다시 빠르게 시작하면 된다고 생각한다", type: "ACTION" },
      { text: "실패 경험에서 다음 아이디어가 나온다고 생각한다", type: "IDEA" },
      { text: "함께하는 사람들이 있으면 이겨낼 수 있다고 믿는다", type: "PEOPLE" }
    ]
  },
  {
    // 주제 11. 팀원 채용 기준  (순서: ACTION-IDEA-PEOPLE-DATA)
    q: "함께 일할 팀원을 뽑는다면 무엇을 가장 크게 보나요?",
    options: [
      { text: "맡은 일을 끝까지 해내는 실행력", type: "ACTION" },
      { text: "남들과 다르게 생각하는 관점", type: "IDEA" },
      { text: "주변과 잘 어울리는 협업 태도", type: "PEOPLE" },
      { text: "근거를 가지고 판단하는 분석력", type: "DATA" }
    ]
  },
  {
    // 주제 12. 창업 성공 조건  (순서: IDEA-PEOPLE-DATA-ACTION)
    q: "창업이 성공하려면 무엇이 가장 필요하다고 생각하나요?",
    options: [
      { text: "남들이 보지 못한 기회를 먼저 발견하는 것", type: "IDEA" },
      { text: "좋은 사람들과 오래 함께 가는 것", type: "PEOPLE" },
      { text: "숫자로 검증된 방향을 꾸준히 밀고 가는 것", type: "DATA" },
      { text: "남보다 먼저 실행하고 끝까지 버티는 것", type: "ACTION" }
    ]
  }
];

/* ---------------------------------------------------------
   2) 결과 유형 데이터
   - 유형 코드(IDEA 등)를 key 로 사용하는 객체입니다.
   - 결과 화면에서 이 데이터를 꺼내 화면에 표시합니다.
--------------------------------------------------------- */
const resultTypes = {
  IDEA: {
    emoji: "💡",
    name: "아이디어 탐험가",
    catch: "남들이 보지 못한 가능성을 먼저 발견하는 사람",
    color: "#f5a623",
    desc:
      "당신은 아직 시장에 없는 것을 상상하고 연결하는 데 강한 창업가입니다. " +
      "익숙한 문제도 새로운 각도에서 다시 정의하며, 사업의 방향과 비전을 만들어내는 출발점 역할을 합니다. " +
      "초기 아이템을 발굴하는 단계와 사업 방향을 바꾸는 피벗 국면에서 특히 힘을 발휘합니다.",
    strength: [
      "기존에 없던 컨셉과 사업 모델을 만들어낸다",
      "서로 다른 분야를 연결해 새로운 기회를 찾는다",
      "비전을 이야기로 풀어내 사람을 설득한다",
      "시장이 바뀌면 유연하게 방향을 바꿀 수 있다"
    ],
    caution: [
      "아이디어가 쌓이는 동안 실행이 뒤로 밀리기 쉽다",
      "검증 없이 확신하면 시장과 어긋날 수 있다"
    ],
    role: [
      "창업 초기 아이템 발굴과 비전 설계 (대표·CEO)",
      "신규 사업 기획, 브랜드 컨셉 총괄",
      "제품의 방향을 잡는 프로덕트 오너(PO)"
    ],
    tip: "실행형(ACTION)·데이터형(DATA) 동료와 팀을 이루면 아이디어가 실제 제품이 됩니다."
  },
  ACTION: {
    emoji: "🚀",
    name: "실행 돌격대장",
    catch: "고민보다 먼저 움직여 결과를 만드는 사람",
    color: "#ef4d5a",
    desc:
      "당신은 완벽한 계획보다 빠른 실행으로 답을 찾아가는 창업가입니다. " +
      "일단 시작해 시장의 반응을 직접 확인하고, 그 과정에서 배우며 개선해 나갑니다. " +
      "초기 스타트업이 가진 속도와 추진력은 대부분 이런 사람에게서 나옵니다.",
    strength: [
      "결정을 미루지 않고 빠르게 실행에 옮긴다",
      "MVP를 만들어 시장 반응을 일찍 확보한다",
      "위기 상황에서 주도적으로 움직인다",
      "팀 전체에 속도감과 추진력을 불어넣는다"
    ],
    caution: [
      "방향 검증 없이 달리면 자원이 낭비될 수 있다",
      "속도를 앞세우다 품질과 기록을 놓치기 쉽다"
    ],
    role: [
      "제품 개발과 초기 영업을 총괄하는 COO",
      "초기 고객 확보를 이끄는 그로스 리드",
      "프로젝트 실행과 일정을 관리하는 PM"
    ],
    tip: "데이터형(DATA) 파트너가 옆에 있으면 빠른 실행이 정확한 실행으로 바뀝니다."
  },
  DATA: {
    emoji: "📊",
    name: "데이터 전략가",
    catch: "숫자로 판단하고 근거로 설득하는 사람",
    color: "#3b6ef6",
    desc:
      "당신은 감이 아니라 근거로 의사결정을 하는 창업가입니다. " +
      "시장과 고객을 숫자로 이해하고, 어떤 지표를 개선해야 사업이 성장하는지 정확히 짚어냅니다. " +
      "사업 규모가 커질수록, 그리고 투자 유치 국면에서 진가가 드러나는 유형입니다.",
    strength: [
      "지표를 기준으로 냉정하게 의사결정한다",
      "위험을 미리 계산해 손실을 줄인다",
      "투자자와 파트너를 근거로 설득할 수 있다",
      "반복해서 성장하는 구조를 설계한다"
    ],
    caution: [
      "분석에 오래 머물러 실행 시점을 놓칠 수 있다",
      "숫자로 증명되지 않는 기회를 지나치기 쉽다"
    ],
    role: [
      "재무와 지표 관리를 총괄하는 CFO·CSO",
      "데이터 기반 마케팅과 그로스 분석 리드",
      "사업 타당성 검토 및 투자 유치 담당"
    ],
    tip: "아이디어형(IDEA)과 함께하면 검증된 새로움을 만들어낼 수 있습니다."
  },
  PEOPLE: {
    emoji: "🤝",
    name: "관계 연결자",
    catch: "사람을 모아 함께 해내게 만드는 사람",
    color: "#22b07d",
    desc:
      "당신은 혼자가 아니라 함께의 힘으로 사업을 키우는 창업가입니다. " +
      "고객의 목소리를 잘 듣고, 팀과 파트너 사이의 신뢰를 만들어냅니다. " +
      "좋은 사람과 좋은 기회가 자연스럽게 모여드는 것이 당신의 가장 큰 자산입니다.",
    strength: [
      "고객과 팀의 진짜 필요를 잘 알아챈다",
      "파트너십과 제휴 기회를 만들어낸다",
      "갈등을 조율해 팀을 오래 유지시킨다",
      "커뮤니티와 팬을 기반으로 성장시킨다"
    ],
    caution: [
      "관계를 의식하다 필요한 결정을 미룰 수 있다",
      "모두를 만족시키려다 방향이 흐려질 수 있다"
    ],
    role: [
      "조직문화와 채용을 이끄는 공동창업자·CHO",
      "B2B 영업과 제휴·파트너십 총괄",
      "커뮤니티 매니저, 고객 성공(CS) 리드"
    ],
    tip: "데이터형(DATA)의 기준이 더해지면 따뜻하면서도 단단한 조직이 됩니다."
  }
};

// 점수 계산과 그래프에서 항상 같은 순서로 쓰기 위한 유형 목록입니다.
const typeKeys = ["IDEA", "ACTION", "DATA", "PEOPLE"];

/* ---------------------------------------------------------
   3) 상태 변수
   - currentIndex : 지금 보여주는 질문 번호 (0부터 시작)
   - answers      : 사용자가 고른 답의 유형을 저장하는 배열
   - nickname     : 사용자가 입력한 닉네임
--------------------------------------------------------- */
let currentIndex = 0;
let answers = [];
let nickname = "";

// 다음 질문으로 넘어가는 중인지 표시합니다.
// 선택 후 0.2초 동안은 true가 되어, 실수로 두 번 클릭해도
// 질문이 두 칸 넘어가거나 결과가 두 번 저장되는 것을 막아줍니다.
let isMoving = false;

/* ---------------------------------------------------------
   4) 화면 요소 미리 가져오기
   - document.getElementById 는 HTML의 id 를 찾아오는 명령입니다.
--------------------------------------------------------- */
const screenStart = document.getElementById("screen-start");
const screenQuiz = document.getElementById("screen-quiz");
const screenResult = document.getElementById("screen-result");

const nicknameInput = document.getElementById("nickname");
const nicknameError = document.getElementById("nickname-error");
const btnStart = document.getElementById("btn-start");
const btnPrev = document.getElementById("btn-prev");
const btnRestart = document.getElementById("btn-restart");

const qCounter = document.getElementById("q-counter");
const qPercent = document.getElementById("q-percent");
const progressBar = document.getElementById("progress-bar");
const qText = document.getElementById("q-text");
const optionsBox = document.getElementById("options");

/* ---------------------------------------------------------
   5) 화면 전환 함수
   - active 클래스가 붙은 화면만 보이도록 CSS에 설정되어 있습니다.
--------------------------------------------------------- */
function showScreen(target) {
  [screenStart, screenQuiz, screenResult].forEach(function (el) {
    el.classList.remove("active");
  });
  target.classList.add("active");
  window.scrollTo({ top: 0, behavior: "smooth" });
}

/* ---------------------------------------------------------
   6) 테스트 시작하기
--------------------------------------------------------- */
function startTest() {
  const value = nicknameInput.value.trim(); // 앞뒤 공백 제거

  // 닉네임이 비어 있으면 안내 문구를 띄우고 멈춥니다.
  if (value === "") {
    nicknameError.textContent = "닉네임을 입력해 주세요.";
    nicknameInput.focus();
    return;
  }

  nickname = value;
  nicknameError.textContent = "";
  currentIndex = 0;
  answers = [];
  isMoving = false; // 이동 잠금 해제

  showScreen(screenQuiz);
  renderQuestion(); // 첫 번째 질문 그리기
}

/* ---------------------------------------------------------
   7) 질문 화면 그리기
   - currentIndex 에 해당하는 질문과 선택지를 화면에 표시합니다.
--------------------------------------------------------- */
function renderQuestion() {
  const current = questions[currentIndex];

  // (1) 질문 번호와 진행률 표시
  qCounter.textContent = "Q" + (currentIndex + 1) + " / " + questions.length;
  const percent = Math.round((currentIndex / questions.length) * 100);
  qPercent.textContent = percent + "%";
  progressBar.style.width = percent + "%";

  // (2) 질문 문장 표시
  qText.textContent = current.q;

  // (3) 기존 선택지를 모두 지우고 새로 만듭니다.
  optionsBox.innerHTML = "";

  current.options.forEach(function (option) {
    const btn = document.createElement("button");
    btn.className = "option";
    btn.type = "button";
    btn.textContent = option.text;

    // 이전에 골랐던 답이 있으면 선택 표시를 남겨둡니다.
    if (answers[currentIndex] === option.type) {
      btn.classList.add("selected");
    }

    // 선택지를 클릭했을 때 실행할 동작을 연결합니다.
    btn.addEventListener("click", function () {
      selectOption(option.type, btn);
    });

    optionsBox.appendChild(btn);
  });

  // (4) 첫 질문에서는 이전 버튼을 비활성화합니다.
  btnPrev.disabled = currentIndex === 0;
}

/* ---------------------------------------------------------
   8) 선택지 클릭 처리
   - 고른 유형을 저장하고 곧바로 다음 질문으로 넘어갑니다.
--------------------------------------------------------- */
function selectOption(type, btnEl) {
  // ★ 이미 다음 질문으로 넘어가는 중이면 무시합니다.
  //   (실수로 빠르게 두 번 눌렀을 때 질문을 건너뛰거나
  //    마지막 문항에서 결과가 두 번 저장되는 것을 막아줍니다)
  if (isMoving) {
    return;
  }
  isMoving = true;

  // 현재 질문의 답을 저장합니다. (다시 고르면 덮어쓰기 됩니다)
  answers[currentIndex] = type;

  // 클릭한 버튼에만 선택 표시를 남깁니다.
  optionsBox.querySelectorAll(".option").forEach(function (b) {
    b.classList.remove("selected");
  });
  btnEl.classList.add("selected");

  // 0.2초 뒤 자동 이동 (선택된 느낌을 잠깐 보여주기 위한 아주 짧은 지연)
  setTimeout(function () {
    isMoving = false; // 이동이 끝났으니 다시 클릭을 받습니다.

    if (currentIndex < questions.length - 1) {
      currentIndex = currentIndex + 1;
      renderQuestion();
    } else {
      showResult(); // 마지막 질문이었다면 결과 화면으로
    }
  }, 200);
}

/* ---------------------------------------------------------
   9) 이전 질문으로 돌아가기
--------------------------------------------------------- */
function goPrev() {
  // 다음 질문으로 넘어가는 중이면 무시합니다. (선택 직후 연타 방지)
  if (isMoving) {
    return;
  }

  if (currentIndex > 0) {
    currentIndex = currentIndex - 1;
    renderQuestion();
  }
}

/* ---------------------------------------------------------
   10) 점수 계산하기
   - 각 유형이 몇 번 선택됐는지 세어서 객체로 돌려줍니다.
     예) { IDEA: 5, ACTION: 3, DATA: 2, PEOPLE: 2 }  → 합계는 항상 12
--------------------------------------------------------- */
function calculateScores() {
  const scores = { IDEA: 0, ACTION: 0, DATA: 0, PEOPLE: 0 };

  answers.forEach(function (type) {
    if (scores[type] !== undefined) {
      scores[type] = scores[type] + 1;
    }
  });

  return scores;
}

/* ---------------------------------------------------------
   11) 점수가 높은 순서대로 유형을 정렬하기
   - 결과 유형(1위)과 보조 유형(2위)을 찾는 데 사용합니다.

   ★ 동점 처리 방법
     이 테스트는 문항마다 유형당 1점이라 동점이 자주 나옵니다.
     그래서 동점일 때는 '마지막 문항(창업 성공 조건)에서 가까운 답'을
     우선합니다. 가치관을 묻는 뒤쪽 문항의 선택을 더 중요하게 보는 방식이며,
     특정 유형이 항상 유리해지는 문제를 막아줍니다.
--------------------------------------------------------- */
function getRankedTypes(scores) {
  // 뒤쪽 문항에서 고른 유형일수록 작은 숫자(=우선순위 높음)를 갖게 만듭니다.
  function tieBreakOrder(type) {
    for (let i = answers.length - 1; i >= 0; i--) {
      if (answers[i] === type) {
        return answers.length - i; // 마지막에 고를수록 1에 가까운 값
      }
    }
    return 999; // 한 번도 고르지 않은 유형은 맨 뒤로
  }

  return typeKeys.slice().sort(function (a, b) {
    if (scores[b] !== scores[a]) {
      return scores[b] - scores[a]; // 점수가 높은 유형이 앞으로
    }
    return tieBreakOrder(a) - tieBreakOrder(b); // 동점이면 위 규칙 적용
  });
}

/* ---------------------------------------------------------
   ★ Supabase 연결하기

   - 페이지가 열릴 때 딱 한 번 실행되어 '연결 통로'를 만들어 둡니다.
   - 연결에 실패해도 테스트 자체는 그대로 동작해야 하므로,
     실패하면 supabaseClient 를 null 로 두고 넘어갑니다.
--------------------------------------------------------- */
let supabaseClient = null; // 연결 성공 시 여기에 담깁니다.

function initSupabase() {
  // (1) CDN이 안 불러와졌는지 확인 (인터넷 차단, 스크립트 순서 문제 등)
  if (typeof window.supabase === "undefined") {
    console.warn(
      "[Supabase] 라이브러리를 불러오지 못했습니다. " +
        "index.html의 CDN <script> 태그가 script.js보다 위에 있는지, " +
        "인터넷 연결이 되는지 확인하세요."
    );
    return;
  }

  // (2) URL과 키를 아직 안 바꿨는지 확인
  if (SUPABASE_URL.indexOf("여기에") !== -1 || SUPABASE_ANON_KEY.indexOf("여기에") !== -1) {
    console.warn(
      "[Supabase] URL과 anon key가 아직 입력되지 않았습니다. " +
        "script.js 맨 위의 SUPABASE_URL / SUPABASE_ANON_KEY 를 수정하세요. " +
        "(설정 전에도 테스트는 정상 동작하며, 결과 저장만 건너뜁니다)"
    );
    return;
  }

  // (3) 연결 통로 만들기
  try {
    supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
    console.log("[Supabase] 연결 준비 완료");
  } catch (e) {
    console.error("[Supabase] 연결 생성 실패:", e);
    supabaseClient = null;
  }
}

/* ---------------------------------------------------------
   ★ 결과를 Supabase에 저장하기

   - async 함수라서 저장이 끝날 때까지 기다리지 않고 진행됩니다.
     그래서 저장이 느리거나 실패해도 결과 화면은 즉시 정상 표시됩니다.
   - 실패하면 화면에는 아무 영향을 주지 않고, 개발자도구 Console(F12)에
     원인을 남깁니다.
--------------------------------------------------------- */
async function saveResultToSupabase(record) {
  // 연결이 안 되어 있으면 저장을 조용히 건너뜁니다.
  if (supabaseClient === null) {
    console.warn("[Supabase] 연결이 없어 저장을 건너뜁니다.", record);
    return;
  }

  try {
    // test_results 테이블에 한 줄(row) 추가하기
    const { error } = await supabaseClient.from("test_results").insert([record]);

    if (error) {
      // Supabase가 돌려준 오류 (테이블 없음, RLS 정책 없음, 컬럼명 불일치 등)
      console.error("[Supabase] 저장 실패:", error.message);
      console.error("  · 상세 내용:", error);
      console.error("  · 보낸 데이터:", record);
      console.error(
        "  · 자주 나오는 원인: ① test_results 테이블이 없음 " +
          "② RLS(insert) 정책 미설정 ③ 컬럼 이름이 다름 ④ anon key 오타"
      );
      return;
    }

    console.log("[Supabase] 저장 성공 ✅", record);
  } catch (e) {
    // 인터넷 끊김 등 네트워크 자체의 문제
    console.error("[Supabase] 네트워크 오류로 저장하지 못했습니다:", e);
  }
}

/* ---------------------------------------------------------
   ★ 전체 참여자 통계 불러오기

   - Supabase의 test_results 테이블에서 유형별 인원 수를 세어 옵니다.
   - 실제 데이터를 전부 내려받지 않고 '개수만' 물어보기 때문에
     참여자가 아무리 많아져도 빠르게 동작합니다.
     ( head: true → 내용은 빼고 개수만 / count: "exact" → 정확한 개수 )
   - 실패하더라도 결과 화면 자체에는 전혀 영향을 주지 않습니다.
--------------------------------------------------------- */
async function loadStats(myType) {
  const totalEl = document.getElementById("stats-total");
  const chartEl = document.getElementById("stats-chart");
  const msgEl = document.getElementById("stats-message");

  // (1) 불러오는 중 상태로 초기화
  totalEl.textContent = "통계를 불러오는 중...";
  chartEl.innerHTML = "";
  msgEl.textContent = "";

  // (2) Supabase 연결이 없으면 안내 문구만 표시하고 끝냅니다.
  if (supabaseClient === null) {
    console.warn("[Supabase] 연결이 없어 통계를 불러오지 못했습니다.");
    showStatsError();
    return;
  }

  try {
    // (3) 유형 4개의 인원 수를 동시에 요청합니다.
    //     Promise.all 은 여러 요청을 한꺼번에 보내고 모두 끝날 때까지 기다립니다.
    const responses = await Promise.all(
      typeKeys.map(function (key) {
        return supabaseClient
          .from("test_results")
          .select("*", { count: "exact", head: true })
          .eq("result_type", key);
      })
    );

    // (4) 응답에서 개수를 꺼내 정리합니다.
    const counts = {};
    let total = 0;

    for (let i = 0; i < typeKeys.length; i++) {
      const res = responses[i];

      if (res.error) {
        throw res.error; // 아래 catch 로 넘어갑니다.
      }

      // count가 null로 올 수도 있으므로 그때는 0으로 처리합니다.
      const n = res.count || 0;
      counts[typeKeys[i]] = n;
      total = total + n;
    }

    console.log("[Supabase] 통계 불러오기 성공 ✅", counts, "총 " + total + "명");

    // (5) 화면에 그리기
    drawStats(counts, total, myType);
  } catch (e) {
    console.error("[Supabase] 통계 불러오기 실패:", e.message || e);
    console.error("  · 상세 내용:", e);
    console.error(
      "  · 자주 나오는 원인: ① RLS의 select(읽기) 정책 미설정 " +
        "② test_results 테이블 없음 ③ 인터넷 연결 문제"
    );
    showStatsError();
  }
}

/* ---------------------------------------------------------
   ★ 통계를 불러오지 못했을 때 표시
--------------------------------------------------------- */
function showStatsError() {
  document.getElementById("stats-total").textContent = "";
  document.getElementById("stats-chart").innerHTML = "";
  document.getElementById("stats-message").textContent = "통계를 불러올 수 없습니다.";
}

/* ---------------------------------------------------------
   ★ 전체 참여자 통계 막대그래프 그리기
   - total(전체 인원)이 0명이어도 오류 없이 0%로 표시됩니다.
--------------------------------------------------------- */
function drawStats(counts, total, myType) {
  const totalEl = document.getElementById("stats-total");
  const chartEl = document.getElementById("stats-chart");
  const msgEl = document.getElementById("stats-message");

  chartEl.innerHTML = "";
  msgEl.textContent = "";

  // (1) 전체 참여자 수 문구
  totalEl.textContent = "지금까지 총 " + total + "명이 참여했어요";

  // (2) 아직 아무도 없으면 안내만 하고 막대는 0%로 그립니다.
  if (total === 0) {
    msgEl.textContent = "아직 참여자가 없습니다. 첫 번째 참여자가 되어보세요!";
  }

  // (3) 유형별 막대 만들기
  typeKeys.forEach(function (key) {
    const info = resultTypes[key];
    const n = counts[key] || 0;

    // ★ 0으로 나누면 오류(NaN)가 나므로, total이 0일 때는 그냥 0%로 둡니다.
    const percent = total === 0 ? 0 : Math.round((n / total) * 100);

    const row = document.createElement("div");
    // 내 유형이면 강조 표시합니다.
    row.className = "chart-row" + (key === myType ? " top" : "");
    row.innerHTML =
      '<span class="chart-label">' + info.emoji + " " + info.name + "</span>" +
      '<span class="chart-track"><span class="chart-fill" style="background:' +
      info.color + '"></span></span>' +
      '<span class="chart-value stats-value">' + percent + "% · " + n + "명</span>";

    chartEl.appendChild(row);

    // 막대가 0%에서부터 자라나는 애니메이션 효과
    setTimeout(function () {
      row.querySelector(".chart-fill").style.width = percent + "%";
    }, 100);
  });
}

/* ---------------------------------------------------------
   12) 결과 화면 표시
--------------------------------------------------------- */
function showResult() {
  const scores = calculateScores();
  const ranked = getRankedTypes(scores);

  const topType = ranked[0]; // 1위 유형
  const subType = ranked[1]; // 2위 유형(보조 성향)
  const result = resultTypes[topType];

  // (1) 유형 고유 색상을 결과 화면 전체에 적용합니다.
  //     CSS 변수(--accent)에 값을 넣으면 CSS 쪽에서 그 색을 그대로 씁니다.
  screenResult.style.setProperty("--accent", result.color);
  screenResult.style.setProperty("--accent-soft", result.color + "1f"); // 끝의 1f는 투명도

  // (2) 상단 기본 정보 채우기
  document.getElementById("result-hello").textContent =
    nickname + "님의 창업가 유형은";
  document.getElementById("result-emoji").textContent = result.emoji;
  document.getElementById("result-key").textContent = topType;
  document.getElementById("result-name").textContent = result.name;
  document.getElementById("result-catch").textContent = result.catch;
  document.getElementById("result-score").textContent =
    "12문항 중 " + scores[topType] + "문항이 이 유형";
  document.getElementById("result-desc").textContent = result.desc;

  // (3) 강점 / 주의할 점 / 추천 창업 역할 목록 채우기
  fillList("result-strength", result.strength);
  fillList("result-caution", result.caution);
  fillList("result-role", result.role);

  // (4) 궁합 팁과 보조 유형 안내
  document.getElementById("result-tip").textContent = result.tip;
  document.getElementById("result-sub").textContent =
    "보조 성향은 " + resultTypes[subType].emoji + " " +
    resultTypes[subType].name + " (" + scores[subType] + "점) 입니다.";

  // (5) 유형별 점수 막대그래프 그리기
  drawChart(scores, topType);

  // (6) 진행률을 100%로 채운 뒤 결과 화면으로 전환
  progressBar.style.width = "100%";
  qPercent.textContent = "100%";
  showScreen(screenResult);

  // (7) 결과를 Supabase에 저장합니다.
  //     ★ 화면을 다 그린 '뒤에' 저장을 시작하고 기다리지 않기 때문에,
  //       저장이 실패하더라도 결과 화면에는 전혀 영향이 없습니다.
  saveResultToSupabase({
    nickname: nickname,
    result_type: topType,
    idea_score: scores.IDEA,
    action_score: scores.ACTION,
    data_score: scores.DATA,
    people_score: scores.PEOPLE,
    created_at: new Date().toISOString() // 저장 시각 (세계 표준시 형식)
  })
    // (8) 저장이 끝난 뒤 전체 참여자 통계를 불러옵니다.
    //     저장 다음에 불러와야 내 결과까지 통계에 포함됩니다.
    //     저장이 실패해도 통계는 그대로 시도합니다.
    .then(function () {
      loadStats(topType);
    })
    .catch(function (e) {
      // 여기까지 오는 일은 거의 없지만, 만약을 대비한 안전장치입니다.
      console.error("[Supabase] 저장/통계 처리 중 예기치 못한 오류:", e);
      showStatsError();
    });
}

/* ---------------------------------------------------------
   13) 목록(ul)에 항목(li)들을 채워 넣는 함수
--------------------------------------------------------- */
function fillList(elementId, items) {
  const ul = document.getElementById(elementId);
  ul.innerHTML = "";

  items.forEach(function (text) {
    const li = document.createElement("li");
    li.textContent = text;
    ul.appendChild(li);
  });
}

/* ---------------------------------------------------------
   14) 유형별 점수 막대그래프 그리기
   - topType 은 1위 유형이며, 해당 줄을 강조 표시합니다.
--------------------------------------------------------- */
function drawChart(scores, topType) {
  const chart = document.getElementById("result-chart");
  chart.innerHTML = "";

  typeKeys.forEach(function (key) {
    const info = resultTypes[key];
    // 12문항이 최대이므로, 12점을 100%로 잡고 막대 길이를 계산합니다.
    const percent = Math.round((scores[key] / questions.length) * 100);

    const row = document.createElement("div");
    row.className = "chart-row" + (key === topType ? " top" : "");
    row.innerHTML =
      '<span class="chart-label">' + info.emoji + " " + info.name + "</span>" +
      '<span class="chart-track"><span class="chart-fill" style="background:' +
      info.color + '"></span></span>' +
      '<span class="chart-value">' + scores[key] + "점</span>";

    chart.appendChild(row);

    // 막대가 0%에서부터 자라나는 애니메이션 효과
    setTimeout(function () {
      row.querySelector(".chart-fill").style.width = percent + "%";
    }, 100);
  });
}

/* ---------------------------------------------------------
   15) 다시 테스트하기 (초기화)
--------------------------------------------------------- */
function restart() {
  currentIndex = 0;
  answers = [];
  isMoving = false; // 이동 잠금 해제
  nicknameInput.value = "";
  nicknameError.textContent = "";
  progressBar.style.width = "0%";
  showScreen(screenStart);
}

/* ---------------------------------------------------------
   16) 버튼과 기능 연결하기 (이벤트 등록)
--------------------------------------------------------- */
btnStart.addEventListener("click", startTest);
btnPrev.addEventListener("click", goPrev);
btnRestart.addEventListener("click", restart);

// 닉네임 입력창에서 Enter 키를 눌러도 시작되게 합니다.
nicknameInput.addEventListener("keydown", function (e) {
  if (e.key === "Enter") {
    startTest();
  }
});

// 다시 입력을 시작하면 오류 문구를 지웁니다.
nicknameInput.addEventListener("input", function () {
  nicknameError.textContent = "";
});

// 페이지가 열릴 때 Supabase 연결을 준비합니다. (실패해도 테스트는 정상 동작)
initSupabase();
